apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "miage-bank.fullname" . }}-secret
  namespace: miage-bank
  labels:
    {{- include "miage-bank.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: mysql-root-password
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: mysql-root-password