apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miage-bank.fullname" . }}-mysql
  namespace: miage-bank
  labels:
    {{- include "miage-bank.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "miage-bank.fullname" . }}-mysql
  template:
    metadata:
      labels:
        app: {{ include "miage-bank.fullname" . }}-mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: mysql-root-password
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
