apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "miage-bank.serviceAccountName" . }}
  namespace: miage-bank
  labels:
    {{- include "miage-bank.labels" . | nindent 4 }}
automountServiceAccountToken: false
