apiVersion: v1
kind: Service
metadata:
  name: {{ include "miage-bank.fullname" . }}
  namespace: miage-bank
  labels:
    {{- include "miage-bank.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "miage-bank.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 10011
      protocol: TCP
      name: http
