apiVersion: v1
kind: ConfigMap
metadata:
  name: amc-comptes-config
  namespace: miage-bank
  labels:
    app: amc-comptes
data:
  SPRING_DATA_MONGODB_HOST: "amc-comptes-mongodb"
  SPRING_DATA_MONGODB_PORT: {{ .Values.mongodb.port | quote }}
  SPRING_DATA_MONGODB_DATABASE: {{ .Values.mongodb.database | quote }}
  SPRING_DATA_MONGODB_USERNAME: {{ .Values.mongodb.username | quote }}
  SPRING_CLOUD_DISCOVERY_ENABLED: "false"
  SPRING_CONFIG_IMPORT: "optional:configserver:"
  SERVER_PORT: "10021"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"