apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: amc-comptes-secret
  namespace: miage-bank
  labels:
    app: amc-comptes
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: mongodb-root-password
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: mongodb-root-password