apiVersion: v1
kind: Service
metadata:
  name: amc-comptes-mongodb
  namespace: miage-bank
  labels:
    app: amc-comptes-mongodb
spec:
  type: ClusterIP
  selector:
    app: amc-comptes-mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP