apiVersion: apps/v1
kind: Deployment
metadata:
  name: miage-bank-front
  namespace: miage-bank
  labels:
    app: miage-bank-front
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: miage-bank-front
  template:
    metadata:
      labels:
        app: miage-bank-front
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 4200
              protocol: TCP
          command: ["node", "server.js"]
          env:
            - name: SERVER_PORT
              value: "4200"
          readinessProbe:
            httpGet:
              path: /
              port: 4200
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 4200
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory | quote }}
              cpu: {{ .Values.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.limits.memory | quote }}
              cpu: {{ .Values.resources.limits.cpu | quote }}