{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: miage-bank-front
  namespace: miage-bank
  labels:
    app: miage-bank-front
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: miage-bank-front
                port:
                  number: {{ .Values.service.port }}
{{- end }}