apiVersion: v1
kind: Service
metadata:
  name: miage-bank-front
  namespace: miage-bank
  labels:
    app: miage-bank-front
spec:
  type: {{ .Values.service.type }}
  selector:
    app: miage-bank-front
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4200
      protocol: TCP