apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: miage-bank
  labels:
    app: eureka
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 10001
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: "10001"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: eureka
            - name: EUREKA_CLIENT_REGISTERWITHEUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCHREGISTRY
              value: "false"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 10001
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 10001
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 10001
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory | quote }}
              cpu: {{ .Values.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.limits.memory | quote }}
              cpu: {{ .Values.resources.limits.cpu | quote }}