apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: miage-bank
  labels:
    app: eureka
spec:
  type: {{ .Values.service.type }}
  selector:
    app: eureka
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 10001
      protocol: TCP